// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpxqjtzwmnjxcjqaauhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtweHFqdHp3bW5qeGNqcWFhdWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDYyMzUsImV4cCI6MjA2OTM4MjIzNX0.RtreZEQg18Sz3lVvfiyCkJhldwjKLHoWo5UiYD21WNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});